# This is a basic workflow to help you get started with Actions

name: LaTeX compilation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - la1_h0*/**
  pull_request:
    branches: [ "master" ]
    paths:
      - la1_h0*/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compiling LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          #pre_compile: "tlmgr update --self && tlmgr update --all"    
          #post_compile: "latexmk -c"
          latexmk_shell_escape: true
          working_directory: la1_h07
          root_file: |
            main.tex

      - name: Compiling LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          #pre_compile: "tlmgr update --self && tlmgr update --all"    
          #post_compile: "latexmk -c"
          latexmk_shell_escape: true
          working_directory: la1_h06
          root_file: |
            main.tex

      - name: Compiling LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          #pre_compile: "tlmgr update --self && tlmgr update --all"    
          #post_compile: "latexmk -c"
          latexmk_shell_escape: true
          working_directory: la1_h05
          root_file: |
            main.tex

      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: la1_thelen_christianrene_h07
          path: la1_h07/main.pdf
